### ISSUE TITLE
错字收集功能未达到预期效果

### ISSUE THREAD

**Issue by Gaeric** [xiaomo-li/typepad#1]
错字收集只在最终提交的时候生效，并未成功收集到练字过程中出错的字；

**Comment by Gaeric** [comment]
复现方法，自定义文章，然后输入错字，可发现错字没有实时更新

**Comment by Gaeric** [comment]
初步测试该问题已解决，谢谢

**Comment by Gaeric** [comment]
目前错字收集功能仍然存在问题:
1. 当错字收集中有200个字时，如果选择发文字数只有50个，当次练习完成后，不会自动发下一段错字
2. 如上述条件，在当次错字练习完成后，左侧的"重复：当前段"按钮会被打开

请设计错字跟打功能，然后重新实现，谢谢

**Comment by Gaeric** [comment]
为什么当初要提意将错字练习做为一个单独的练习方式放在左侧，而不是一个仅仅做为一篇文章，然后做特殊处理:
1. 错字练习需要在本次练习完成之后清除当前错字内容，这和左侧的功能"重打" "乱序"等有冲突关系
2. 错字在练习完成后自动发下一段，这个左侧的自动发文功能冲突

所以请重新审视目前的错字练习需求，选择合适的方式修正该功能

**Comment by xiaomo-li** [comment]
错字练习与重复段等功能的兼容性问题已修复。

**Comment by Gaeric** [comment]
错字练习:
finish时未刷新错字排行
finish时未刷新剩余段数

**Comment by xiaomo-li** [comment]
done

**Comment by xiaomo-li** [comment]
练习模式已更新

**Comment by Gaeric** [comment]
功能改进：所有错字练习完成且没有新增错字时，关闭错字收集模式

**Comment by xiaomo-li** [comment]
关闭什么？

**Comment by xiaomo-li** [comment]
done

**Comment by Gaeric** [comment]
nice
